services:
  php-fpm:
    container_name: invoiceshelf-dev-php
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      args:
        - UID=${USRID:-1000}
        - GID=${GRPID:-1000}
      target: development
    volumes:
      - ../../:/var/www/html
    networks:
      - invoiceshelf-dev

  nginx:
    container_name: invoiceshelf-dev-nginx
    build:
      context: ../../
      dockerfile: docker/development/nginx.Dockerfile
    environment:
      - "PHP_FPM_HOST=php-fpm:9000"
    ports:
      - '80:80'
    volumes:
      - ../../:/var/www/html
    networks:
      invoiceshelf-dev:
        aliases:
          - invoiceshelf.test

  adminer:
    container_name: invoiceshelf-dev-adminer
    build:
      context: ../../
      dockerfile: docker/development/adminer/Dockerfile
    environment:
      ADMINER_PLUGINS: tables-filter
      ADMINER_DESIGN: konya
    volumes:
      - ../../database:/database
    ports:
      - '8080:8080'
    networks:
      - invoiceshelf-dev

  mail:
    container_name: invoiceshelf-dev-mailpit
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - invoiceshelf-dev

  pdf:
    image: gotenberg/gotenberg:8
    networks:
      - invoiceshelf-dev

networks:
  invoiceshelf-dev:
