blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.invoiceshelf.com/
    about: App documentation.
  - name: Translation issue
    url: https://crowdin.com/project/invoiceshelf
    about: Help improve translations on Crowdin.
  - name: Support, Question & Discussion - Official Discord Server
    url: https://discord.gg/hwg2FtwWHW
    about: Post your questions and join the discussion. You can participate in chats on every channel.
